import './globals.css'
import { BioRhyme } from 'next/font/google'
import StickyNavbar from '../components/StickyNavbar'

const bioRhyme = BioRhyme({ weight: "400", subsets: ['latin-ext']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bioRhyme.className}>
        <div>
          <StickyNavbar />
          {children}

        </div>

        </body>
    </html>
  )
}
